apiVersion: v1
kind: Service
metadata:
  name: fifa-backend-service
  namespace: fifa-app
spec:
  selector:
    app: fifa-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
