apiVersion: v1
kind: Service
metadata:
  name: fifa-frontend-service
  namespace: fifa-app
spec:
  selector:
    app: fifa-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
